#!/bin/bash

PROTO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NANOPB_PATH="$(readlink -f "${PROTO_DIR}/../../../platform/spark/device-os/third_party/nanopb/nanopb")"
PROTOC_NANOPB_PLUGIN="${NANOPB_PATH}/generator/protoc-gen-nanopb"
if [[ "${OSTYPE}" == "msys" ]]; then
	PROTOC_NANOPB_PLUGIN="${PROTOC_NANOPB_PLUGIN}.bat" # add .bat when on windows
fi
PROTOC_INCLUDE_PATH="-I${PROTO_DIR} -I${NANOPB_PATH}/generator"

pushd "$PROTO_DIR" > /dev/null # .option files are read from execution directory, so have to cd into this dir 
mkdir -p "tmp_cpp"
mkdir -p "cpp"

protoc ${PROTOC_INCLUDE_PATH} \
--nanopb_out=tmp_cpp \
${PROTO_DIR}/*.proto \
--proto_path=${PROTO_DIR} \
--plugin=protoc-gen-nanopb=${PROTOC_NANOPB_PLUGIN}

rm tmp_cpp/nanopb.* # nanopb.h and nanopb.c are not needed and generate compiler warnings when they are not removed

# copy only modified files to source dir
cd tmp_cpp
for file in *
do
  # remove timestamp from file (or it will always be modified)
  sed -i '/Generated by nanopb-/d' "${file}"
  # copy modified files
  rsync --checksum "$file" "../cpp/${file}"
done
popd > /dev/null
